language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: d4JKe5ek6CKfadcd1y9A9TTdCFD/uCIMCH1RFXMFjXzgk7UCMnapExWZn6P3G5UN0BXtbfz35ZlJngjUgbP4Hu4htda6iB/Ps8W1mHPZ+m+kZBWd3An3WgXmEwM8VibuYTossTqmwNROW/T1VdON3no8Wx4kaBJE9ofNWkTQ9jTr56DeqQSErya44NcV3ijdJA3H0YsnONPgkbc+IiqZ11cCQvFe4k0SQkXJbGwDBBHuWjImw+uBq2df5tRSZgn7ubEY0NDKhm0uXXn2gML1Bix6gn0hy57SHNo6nb+5DDZ8/cBIV8ARrR1Nx20LU+hmj2Z2Z6DS7tNRrt3PXP9mUNNGBNZLYydH8pckIGK/adNhuqLr+A+go1sxc3q8fuyT/7KaSYA0amn/tJvSkIq9SE3SPjBL7icodW/C2lbJBBldbzTfKyB/Bv3dNn89q9Ru/seOUvZ6tq0WfM7pZc1ZC8B8/0N/OFQYy95giY1hJryGDBE3sItS/4HdqaMb23etuelH5UdCFnRuYU0WW3hs0ftomsAD/CfoypHwxeuGfe9GNKEHbLyQHhLtajD+VUPeXBbzMdZbSMV19NzTq3r3P9W724bjI7oiiV20SB3JPuOmtxCs080Ge0VdS2/KwShegP6/g8Lb5Y+SIwPEqpV9zgXxZMqvyApyP43ONnN8se4=
  - secure: JZebxyKJQSyWeW51nO+LLF0JuW0yJIhLGcGT3AFUDa9Rsw6bl6mPcECq2kJbtMh6SxHWIj1hfkwM51jClTJ8X24aN7juPWQdAwiRYVIQ6kcMSCP0ZWx7yVF6NtTzarHYMsaKi9OpHCtbigaI0FMT9zjPLj4HheTyavMjztn3vlnJ6Nsz6F/CEFOOHbt135nNP4fwgNxI4xD9v3U5lfGWgBBic8fnKA58/gPlIdV2QsDbMlhIOriYllUhfcX9+3vDPyVomqhi3e2Tr7HkzoOdaOVu2pIoC0653w3lJDwWkuMh6w1TRC3O1g01h+KgUMlnD3B8fGVk4WKz2ATMJPba651FBBI+egp7qhdKG2N6VkbHmzDLqt0rEri/MnrdStEI2NcP9SZYz2MUnaHCIfBnf9fdpwvNGIRAci3UiFZY1fb1w3l60wnmHolojFtZUlMN7t5Kt+OX1QLYejfNkZ28xNZPVzVIwd7IY0ktSUBIhEuKolsmkBZE0/Bqh2EwGK+RhxQNtjzTvamMmhddspJLNsKWvqDV1WU60IdOahT38D+JVPGcxbijmpL79bscMW7uZqz6SbpN7KbpzCvHd+TkeQbjWrMTcrwczAc2EThZ+inlvtsE3NCIUpXZXQlEQeeHwR7nwZK5UfqmSbpNzN6Bj4PVY7Zb4DiqgKkkZSBT5p8=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
  hosts:
    - cozy.local
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.5 - --user
- travis_retry pip3.5 install --user transifex-client
- install -m0644 .transifexrc.tpl ~/.transifexrc
- echo "password = $TX_PASSWD" >> ~/.transifexrc
script:
- yarn run build
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy -- --branch=build
- test $TRAVIS_BRANCH = "prod" && yarn run deploy -- --branch=latest
